language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

install:
    - composer --prefer-source install

script:
    - php vendor/bin/phpunit
