bldr:
    profiles:
        tdd:
            description: Local Development Profile
            tasks:
                - test
                - watch
        cs:
            description: fix cs for once
            tasks:
                - runFixer
                - loadFixtures
        rebase:
            description: Rebase flow
            tasks:
                - gushRebase
        merge:
            description: merge flow
            tasks:
                - gushMerge
